<?php
declare(strict_types=1);

namespace Tests\Unit\RateLimiter;

use Maatify\Verification\Domain\Enum\IdentityTypeEnum;
use Maatify\Verification\Domain\Enum\VerificationPurposeEnum;
use Maatify\Verification\Infrastructure\RateLimiter\RedisRateLimiter;
use PHPUnit\Framework\TestCase;

class RedisRateLimiterTest extends TestCase
{
    private ?\Redis $redis = null;
    private ?RedisRateLimiter $limiter = null;
    private string $prefix = 'test_prefix';

    protected function setUp(): void
    {
        if (!extension_loaded('redis')) {
            $this->markTestSkipped('Redis extension not installed.');
        }

        try {
            $this->redis = new \Redis();
            $host = getenv('REDIS_HOST') ?: '127.0.0.1';
            $port = (int)(getenv('REDIS_PORT') ?: 6379);

            if (!@$this->redis->connect($host, $port)) {
                $this->markTestSkipped('Could not connect to Redis server.');
            }

            // Simple ping to ensure connection is actually alive
            if (!@$this->redis->ping()) {
                $this->markTestSkipped('Redis server is not responding to ping.');
            }

            $this->limiter = new RedisRateLimiter($this->redis, $this->prefix);
        } catch (\Exception $e) {
            $this->markTestSkipped('Redis connection failed: ' . $e->getMessage());
        }
    }

    protected function tearDown(): void
    {
        if ($this->redis) {
            try {
                // Instead of KEYS, we can use an iterator (SCAN) to safely find keys, or just
                // manually delete the exact keys we know we created.
                $iterator = null;

                do {
                    $keys = $this->redis->scan($iterator, $this->prefix . ':*');

                    if ($keys !== false) {
                        $this->redis->del($keys);
                    }

                } while ($iterator !== 0);
            } catch (\Exception $e) {
                // Ignore cleanup errors if server went away
            } finally {
                try {
                    $this->redis->close();
                } catch (\Exception $e) {}
            }
        }
    }

    public function testRateLimiterRecordsHit(): void
    {
        if (!$this->limiter || !$this->redis) {
            $this->markTestSkipped('Redis not available');
        }

        /** @var \Redis $redis */
        $redis = $this->redis;
        /** @var RedisRateLimiter $limiter */
        $limiter = $this->limiter;

        try {
            $limiter->hit(
                IdentityTypeEnum::User,
                'user1',
                VerificationPurposeEnum::EmailVerification
            );

            // Fetch keys safely via SCAN. Broaden the pattern to find the exact key
            // regardless of internal enum serialization or suffixes.
            $iterator = null;
            $foundKeys = [];

            do {
                $scannedKeys = $redis->scan($iterator, $this->prefix . ':*');

                if (is_array($scannedKeys)) {
                    foreach ($scannedKeys as $k) {
                        $foundKeys[] = $k;
                    }
                }

            } while ($iterator !== 0 && $iterator !== null); // Ensure safe cursor handling

            $this->assertNotEmpty($foundKeys, 'No rate limiter keys were found in Redis.');

            // Use the actual key generated by the limiter
            $actualKey = $foundKeys[0];

            $val = $redis->get($actualKey);
            $this->assertIsString($val, "Value for key {$actualKey} should be a string.");
            $this->assertEquals(1, (int)$val);

            // Test second hit
            $limiter->hit(
                IdentityTypeEnum::User,
                'user1',
                VerificationPurposeEnum::EmailVerification
            );

            $val = $redis->get($actualKey);
            $this->assertIsString($val);
            $this->assertEquals(2, (int)$val);
        } catch (\RedisException $e) {
            $this->markTestSkipped('Redis server went away during test: ' . $e->getMessage());
        }
    }
}
